#########################################################################
#      Copyright (C) 2020        Sebastian Francisco Colomar Bauza      #
#      SPDX-License-Identifier:  GPL-2.0-only                           #
#########################################################################
services:
  spring-petclinic-svc:
    deploy:
      placement:
        constraints:
        - node.role == manager
    image: ipuertas/spring-petclinic
    ports:
      - 8080:8080
version: '3.8'
#########################################################################
